### ISSUE TITLE
希望添加状态栏时间显示秒数！

### ISSUE THREAD

**Issue by yujincheng08** [yonghen/chimi-#1]
模块很好用！！😁如果能在状态栏添加秒数就好了！目前我都只能考反编译SystemUI来添加的，每次更新系统都得弄一遍很麻烦。

另外可以开通捐赠渠道，我也想支持一下作者😁😁

**Comment by yonghen** [comment]
后续可能会增加

**Comment by ilolipopi** [comment]
可以用一个叫“秒时钟”的App

**Comment by yujincheng08** [comment]
😉赞！
