### ISSUE TITLE
k20p开启时间居中会状态栏消失

### ISSUE THREAD

**Issue by jmzd315221** [yonghen/chimi-#104]
优化过系统界面也重新勾选chimi也清除过数据了，时间居右可以生效。开启时间居中状态栏就会消失，像开启隐藏状态栏似的。

**Comment by yonghen** [comment]
是MIUI12.5吗？

**Comment by jmzd315221** [comment]
> 是MIUI12.5吗？

是的，21.2.3

**Comment by yonghen** [comment]
可以提供日志看下吗，我这没有问题

**Comment by jmzd315221** [comment]
> 可以提供日志看下吗，我这没有问题

请问该怎么提供日志？小米的日志抓取吗？

**Comment by yonghen** [comment]
edxpoed/lsposed里的日志

**Comment by jmzd315221** [comment]
> edxpoed/lsposed里的日志

好的
https://wwa.lanzous.com/iTPKdlmoh0j

**Comment by yonghen** [comment]
emmm并没有发现有hook错误，很抱歉可能修复不了这个问题
