### ISSUE TITLE
21.4.28 状态栏温度显示失效

### ISSUE THREAD

**Issue by Qi-yuxuan** [yonghen/chimi-#114]
![Screenshot_2021-05-01-15-35-23-240_com.absinthe.libchecker.jpg](https://user-images.githubusercontent.com/62003656/116774994-e5274500-aa25-11eb-886e-e489d4ec0bbb.jpg)
更新快照显示systemui有更新，只有我一个人失效吗QAQ
MIUI版本21.4.28
机型K30PRO

**Comment by xiaowine** [comment]
红米K20同上

**Comment by Jun041** [comment]
小米9同上

**Comment by NameExist3** [comment]
同机型21.4.26也失效了
