### ISSUE TITLE
太极上下载管理闪退

### ISSUE THREAD

**Issue by AceMONKEY519** [yonghen/chimi-#12]
chimi2.2.22，MIUI10 9.2.25

**Comment by AceMONKEY519** [comment]
应用管理组件也闪退

**Comment by yonghen** [comment]
@AceMONKEY519 可能是下载管理更新了代码，可在太极移除相关的应用暂时解决问题

**Comment by AceMONKEY519** [comment]
XPosed版，已解密data分区，重启第一次指纹解锁依旧无法使用，上个版本2.2.24可以用。

另外可否加入状态栏显示秒钟功能？以及加入通知音量与铃声分开调节功能。

蟹蟹。

**Comment by xinyonghu1** [comment]
@AceMONKEY519 这个只能等待更新，我也是同样情况，不过指纹那个我可以用，其他功能无效，2.2.14才全功能适配
