### ISSUE TITLE
状态栏的相关功能基本失效

### ISSUE THREAD

**Issue by 2927282519** [yonghen/chimi-#123]
😭😭😭

**Comment by 2927282519** [comment]
系统是MIUI12.5.4，稳定版

**Comment by joamg** [comment]
+1, 12.5.1小米8

**Comment by yonghen** [comment]
开发版已经更新支持

**Comment by 2927282519** [comment]
🐂🍺



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月11日(周三) 上午6:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yonghen/chimi-] 状态栏的相关功能基本失效 (#123)




 
开发版已经更新支持
