### ISSUE TITLE
miui状态栏去白边下面的更多设置希望数值不要限定在整数

### ISSUE THREAD

**Issue by AllrightChou** [yonghen/chimi-#13]
如题，当前最大数值是三位数整数，但是比如在米8上匹配那个Android O样式音乐通知的最佳数值是136.6，多0.4就会在下面有一个白线，少0.6锁屏状态下歌曲信息就会展不开，因此希望能将数值类型改成浮点型限制一两位小数，而不是限制在整型。
谢谢。

**Comment by yonghen** [comment]
@AllrightChou 目前无法解决，因为使用的是hook，不知如何直接把浮点转换成像素值，目前使用applyDimension方法来代替，如果你有更好的方法可以代替，希望能教我。

**Comment by AllrightChou** [comment]
sorry我没有什么好的解决方案，我只知道反编译miuiSystemUI.apk然后改相关xml的元素值。辛苦了:)

**Comment by yonghen** [comment]
> @yonghen抱歉我没有什么好的解决方案，我只知道反编译miuiSystemUI.apk然后改相关xml的元素值。辛苦了:)

下个版本更新新的方法可输入浮点数值，更新后如果功能可行的话请告诉我
