### ISSUE TITLE
CPU Battery temperature status bar position does not work

### ISSUE THREAD

**Issue by tuyennn** [yonghen/chimi-#135]
MIUI 12.5.5 Enhanced Edition
Xiaomi 10 Ultra
MIUI 12.5.6
Redmi Note 10 Pro

ChiMi 4.08.10

#Steps:
Using with Position 2
![Screenshot_2021-08-19-22-32-51-233_chili.xposed.chimi.jpg](https://user-images.githubusercontent.com/4010395/130098543-43be0275-25e4-48e0-8eb6-bec3ba264105.jpg)

#Current: 
- Temperature doesn't shown

#Expect:
- Temperature should shown as configuration
![IMG_20210819_223401.jpg](https://user-images.githubusercontent.com/4010395/130098858-80ef18c9-37c5-427a-a649-5539a36dc9bd.jpg)

**Comment by RealFsh** [comment]
Stable ROM is not supported

**Comment by tuyennn** [comment]
``Stable ROM is not supported``

That's not what I expected Stable but not supported. LOL, dumb
