### ISSUE TITLE
2个建议

### ISSUE THREAD

**Issue by huangsijun17** [yonghen/chimi-#15]
1. 可否加入屏蔽状态栏的双开logo
2. 可否在锁屏界面加入急救信息(com.android.emergency)的入口？

**Comment by yonghen** [comment]
@huangsijun17 双开logo状态栏好像没有啥图标啊，第二个考虑一下吧

**Comment by huangsijun17** [comment]
用系统自带的双开，会有一个 **两个圆角方形** 的图标。

**Comment by yonghen** [comment]
> 用系统自带的双开，一个会有**两个圆角方形**的图标种植。

看到了，那个图标提醒挺好的，可以区分是否为双开应用，感觉没必要屏蔽吧

**Comment by huangsijun17** [comment]
> > 用系统自带的双开，一个会有**两个圆角方形**的图标种植。
> 
> 看到了，那个图标提醒挺好的，可以区分是否为双开应用，感觉没必要屏蔽吧

但某些时候，反而会画蛇添足，显得碍眼。而且，在多任务界面是可以看到每个应用是否为双开的。
建议添加功能为可关闭。
