### ISSUE TITLE
双排温度位置二上下抖动

### ISSUE THREAD

**Issue by Steve-cn** [yonghen/chimi-#161]
更新后的版本当选择双排温度位置二时，温度会上下抖动（桌面下滑唤起通知中心的时候）

**Comment by yonghen** [comment]
什么机型 miui版本 Android版本

**Comment by Steve-cn** [comment]
> 什么机型 miui版本 Android版本

红米k30pro MIUI 13 V13.0.3.1.27.DEV 安卓12

**Comment by yonghen** [comment]
> > 什么机型 miui版本 Android版本
> 
> 红米k30pro MIUI 13 V13.0.3.1.27.DEV 安卓12

只是跳动，还是会偏移？

**Comment by Steve-cn** [comment]
> > > 什么机型 miui版本 Android版本
> > 
> > 红米k30pro MIUI 13 V13.0.3.1.27.DEV 安卓12
> 
> 只是跳动，还是会偏移？

这是录屏https://cp.anyknew.com/s/iqvy

**Comment by yonghen** [comment]
5.03增加兼容模式，可以试试
