### ISSUE TITLE
温度在通知栏最左边和时间右边来回跳

### ISSUE THREAD

**Issue by Hans155922** [yonghen/chimi-#162]
rt
![Screenshot_2022-04-24-21-04-03-500_chili xposed chimi](https://user-images.githubusercontent.com/35620329/164977971-b7945d48-2404-401b-a140-dc8887bfc02d.png)
![Screenshot_2022-04-24-21-04-12-293_chili xposed chimi](https://user-images.githubusercontent.com/35620329/164977979-3ff0f412-75a7-4509-a83b-b3bae45897c4.png)
![Screenshot_2022-04-24-21-04-12-293_chili xposed chimi](https://user-images.githubusercontent.com/35620329/164977980-e13cc17a-2ec2-40b4-b939-d320b822a921.png)

**Comment by yonghen** [comment]
什么机型 miui版本 Android版本

**Comment by Hans155922** [comment]
> 什么机型 miui版本 Android版本

小米10ultra 22.4.20 安卓12

**Comment by yonghen** [comment]
> > 什么机型 miui版本 Android版本
> 
> 小米10ultra 22.4.20 安卓12

上个版本会这样吗

**Comment by Hans155922** [comment]
> > > 什么机型 miui版本 Android版本
> > 
> > 
> > 小米10ultra 22.4.20 安卓12
> 
> 上个版本会这样吗

上个版本没事，今天早上也是22.4.20没问题，冻结电量和性能后才出现的

**Comment by yonghen** [comment]
> > > > 什么机型 miui版本 Android版本
> > > 
> > > 
> > > 小米10ultra 22.4.20 安卓12
> > 
> > 上个版本会这样吗
> 
> 上个版本没事，今天早上也是22.4.20没问题，冻结电量和性能后才出现的

我是说上个版本的ChiMi会这样吗，你可以试试上个版本的ChiMi

**Comment by Hans155922** [comment]
> > > > > 什么机型 miui版本 Android版本
> > > > 
> > > > 
> > > > 小米10ultra 22.4.20 安卓12
> > > 
> > > 
> > > 上个版本会这样吗
> > 
> > 
> > 上个版本没事，今天早上也是22.4.20没问题，冻结电量和性能后才出现的
> 
> 我是说上个版本的ChiMi会这样吗，你可以试试上个版本的ChiMi

现在重新安装上个版本，重启后还是闪

**Comment by yonghen** [comment]
> > > > > > 什么机型 miui版本 Android版本
> > > > > 
> > > > > 
> > > > > 小米10ultra 22.4.20 安卓12
> > > > 
> > > > 
> > > > 上个版本会这样吗
> > > 
> > > 
> > > 上个版本没事，今天早上也是22.4.20没问题，冻结电量和性能后才出现的
> > 
> > 我是说上个版本的ChiMi会这样吗，你可以试试上个版本的ChiMi
> 
> 现在重新安装上个版本，重启后还是闪

那可能是其他问题，只能先这样了，用位置2吧

**Comment by Hans155922** [comment]
> > > > > > > 什么机型 miui版本 Android版本
> > > > > > 
> > > > > > 
> > > > > > 小米10ultra 22.4.20 安卓12
> > > > > 
> > > > > 
> > > > > 上个版本会这样吗
> > > > 
> > > > 
> > > > 上个版本没事，今天早上也是22.4.20没问题，冻结电量和性能后才出现的
> > > 
> > > 
> > > 我是说上个版本的ChiMi会这样吗，你可以试试上个版本的ChiMi
> > 
> > 
> > 现在重新安装上个版本，重启后还是闪
> 
> 那可能是其他问题，只能先这样了，用位置2吧

好，谢谢大佬，用②正常了

**Comment by yonghen** [comment]
5.03应该修复了

**Comment by Hans155922** [comment]
我更新，重启后依旧乱跳

**Comment by Hans155922** [comment]
> 5.03应该修复了

我更新，重启后依旧乱跳
