### ISSUE TITLE
双排温度变色抽风

### ISSUE THREAD

**Issue by Kaeisol** [yonghen/chimi-#169]
有时候待久了换到其他软件背景颜色不一样就双排温度没变还是之前的颜色 其他状态栏图标都变色了 时不时就会这样

**Comment by yonghen** [comment]
可能跟你装的某些其他模块有关，我目前一直用着没出现过这问题，群里也没有其他人反馈有这问题

**Comment by Kaeisol** [comment]
好的 我之前也不会 把手机恢复出厂就出现我还以为是bug 打扰打扰 感谢
