### ISSUE TITLE
关于太极版吃米反馈

### ISSUE THREAD

**Issue by LHH2857263020** [yonghen/chimi-#17]
关于我的设备 MI6X 8.1 MIUI10 9.1.24 开发版 在面具版 太极5.01 Chimi 2.2.27 出现的问题 -系统界面-无法屏蔽 后台运行提示 和应用上层显示 ~其他功能都能正常使用 望知悉～(￣▽￣～)

**Comment by LHH2857263020** [comment]
在2.2.14版本全功能正常使用

**Comment by yonghen** [comment]
@LHH2857263020 可是我测试是正常的...下个版本更新你再看看失效没有。
