### ISSUE TITLE
增加双击状态栏锁屏以及恢复MIUI通知重要程度功能

### ISSUE THREAD

**Issue by banzhiz** [yonghen/chimi-#171]
双击状态栏锁屏可以解放电源键，通知重要程度可以隐藏监控类软件通知图标

**Comment by CheJianLin** [comment]
#chimi# 
【Chimi导致部分软件闪退。】
目前吃米版本V5.04.09，
以前都没有问题，
不管是升级，停用，或者卸载吃米，
反正就是不能动它。
部分软件，
比如微信，Twitter， GooGle Play都会闪退。
一直找不到原因，
有朋友知道怎么破么？
万分感谢。
#chimi#
