### ISSUE TITLE
建议将双排网速显示与双排温度显示对齐

### ISSUE THREAD

**Issue by Zh40Le1ZOOB** [yonghen/chimi-#172]
如图，两项存在偏移，强迫症表示很难受（
![IMG_20220527_214138](https://user-images.githubusercontent.com/97139537/170711733-d4fc91ff-4185-4442-946e-1173332ace99.jpg)

**Comment by yonghen** [comment]
你的版本是开发版吗？在我两部手机上都无法重现这个bug，默认是对齐的。

**Comment by Zh40Le1ZOOB** [comment]
> 你的版本是开发版吗？在我两部手机上都无法重现这个bug，默认是对齐的。

Redmi Note 9 5G
MIUI 13.0.1.0 稳定版
确认字体模块无影响
所有项开启双排字体加粗，双排字体最大，双排间隔最大
这是刚截的效果图（已多次重启）
![IMG_20220530_120446](https://user-images.githubusercontent.com/97139537/170915224-2b766439-53d1-4b02-98b1-b9c190131313.jpg)

**Comment by Zh40Le1ZOOB** [comment]
> 你的版本是开发版吗？在我两部手机上都无法重现这个bug，默认是对齐的。

这是关闭字体模块的效果图
![IMG_20220530_120953](https://user-images.githubusercontent.com/97139537/170915669-a7944b95-f606-4e14-a701-c45621c3de10.jpg)

**Comment by Zh40Le1ZOOB** [comment]
> 你的版本是开发版吗？在我两部手机上都无法重现这个bug，默认是对齐的。

顺带提一下，没有使用其它任何修改状态栏的模块

**Comment by yonghen** [comment]
1.状态栏空间不足，隐藏一些图标解决。
2.项目基于开发版开发，不保证其他版本能适配。
