### ISSUE TITLE
Notification and control center date pattern 

### ISSUE THREAD

**Issue by andrea-musci** [yonghen/chimi-#173]
Hi,
The custom pattern string for notification and control center is parsed in a strange way.
For instance, if I put MMM I'm expecting short month name (example: 'Jul' for July) but I get full month name.
With the letter 'w' I should get week number, but I get nothing but a white space.
So what are the possible pattern strings? Is it Java or Android standard date pattern?

Thx

**Comment by yonghen** [comment]
Its date pattern should be the date pattern rewritten by MIUI. I just hook its date string.In the English language of the CN version of MIUI, I enter MMM. It is the short month name, enter E is the week.

**Comment by andrea-musci** [comment]
Thanks for clarifying
