### ISSUE TITLE
适配折叠平请求

### ISSUE THREAD

**Issue by shugo-chara** [yonghen/chimi-#174]
在fold折叠屏上功能使用正常，但是双排网速内外屏大小显示不一致。如果在内屏设置正常后，外屏就会便大，反之内屏会变大。
![Screenshot_2022-05-31-22-05-09-375_chili xposed chimi](https://user-images.githubusercontent.com/20610965/171180519-d2ff916e-4f93-48c2-98e0-4a94f858edd9.png)

**Comment by yonghen** [comment]
没有折叠屏手机，抱歉，我无法适配
