### ISSUE TITLE
长时间待机，系统界面会无响应，锁屏界面会黑屏，不能进入系统，要过一会才恢复

### ISSUE THREAD

**Issue by jumaoli** [yonghen/chimi-#177]
长时间待机，系统界面会无响应，锁屏界面会黑屏，不能进入系统，要过一会才恢复,用chimi会这样。用woobox就不会

**Comment by yonghen** [comment]
不要同时使用其他修改miui系统的插件，请确定好具体是哪个插件，以前的确出现过，但在5.31理论上已经解决了，备用机待机一天再打开也是正常的。
