### ISSUE TITLE
状态栏显示温度失效

### ISSUE THREAD

**Issue by Sdky** [yonghen/chimi-#178]
状态栏无法显示CPU/电池温度
手机型号：小米11
系统版本号：MIUI 13 V13.0.71.40.DEV

![Screenshot_2022-06-26-17-35-54-573_chili xposed chimi](https://user-images.githubusercontent.com/29597396/175808506-eb7b93a1-c01b-49d7-9a1e-8e6d1ddb9308.jpg)
![Screenshot_2022-06-26-17-36-24-198_com android shell](https://user-images.githubusercontent.com/29597396/175808510-0c3546a2-4271-4b46-b1ba-2b16f3218e19.jpg)

**Comment by yonghen** [comment]
是官方包吗，有没有刷其他magisk插件，或者使用了其他修改系统界面的xposed插件，我两部手机都是40dev，没有问题

**Comment by Sdky** [comment]
是官改包，只安装了这些

![Screenshot_2022-06-26-18-48-33-473_com android settings](https://user-images.githubusercontent.com/29597396/175810743-e68e594d-9a13-4644-b788-7836406cc852.jpg)
![Screenshot_2022-06-26-18-47-56-615_com topjohnwu magisk](https://user-images.githubusercontent.com/29597396/175810752-67dbed81-6f5d-485d-a7ca-69339dfef174.jpg)
![Screenshot_2022-06-26-18-48-24-397_com android shell](https://user-images.githubusercontent.com/29597396/175810757-3b18764c-b682-4b3a-807c-8957c50549d6.jpg)

**Comment by yonghen** [comment]
官改包可能对状态栏有改动，不在适配范围内，抱歉

**Comment by Sdky** [comment]
省电与电池-电池中显示温度这里也失效了
![Screenshot_2022-06-26-19-19-46-152_chili xposed chimi](https://user-images.githubusercontent.com/29597396/175811793-d882b5d5-4322-4676-afaf-ecf3c74d8e05.jpg)
![Screenshot_2022-06-26-19-19-54-963_com miui securitycenter](https://user-images.githubusercontent.com/29597396/175811796-153abd27-7ea3-4597-a4d2-0df990422c54.jpg)

**Comment by yonghen** [comment]
> 省电与电池-电池中显示温度这里也失效了
> ![Screenshot_2022-06-26-19-19-46-152_chili xposed chimi](https://user-images.githubusercontent.com/29597396/175811793-d882b5d5-4322-4676-afaf-ecf3c74d8e05.jpg)
> ![Screenshot_2022-06-26-19-19-54-963_com miui securitycenter](https://user-images.githubusercontent.com/29597396/175811796-153abd27-7ea3-4597-a4d2-0df990422c54.jpg)
> 
> 

这个下个版本修复

**Comment by sugelamydi** [comment]
官方包貌似也是这样，位置2无效
