### ISSUE TITLE
bug＋建议

### ISSUE THREAD

**Issue by yanareat** [yonghen/chimi-#19]
1.不知道是不是个例，我的耗电曲线图显示wlan一直开着，但我其实没有开！
2.平均内存使用量的设置app图标看不见，占比条位置不对
3.我不知道是专门设计的，还是bug，我不能隐藏系统软件

**Comment by yanareat** [comment]
系统为，MIUI9，安卓6，第三方rec，supersu，最新版本chimi，框架

**Comment by yonghen** [comment]
@yanareat 1、2未知 ，3的确屏蔽了系统软件

**Comment by yanareat** [comment]
我想隐藏系统的软件，怎么才可以？

**Comment by yonghen** [comment]
> 我想隐藏系统的软件，怎么才可以？

下个版本不在支持6.0，以前的版本可以隐藏，而且对MIUI9支持比较好
