### ISSUE TITLE
有考虑过增加跳过警告弹窗的功能吗

### ISSUE THREAD

**Issue by yhlzkd** [yonghen/chimi-#231]
MIUI现在有很多界面有警告弹窗，比如打开软件的无障碍功能时会弹警告，等待10s以后才能打开

**Comment by shadowxhero** [comment]
如果是无障碍跳过的话，现在已经就支持了，手机管家-跳过警告时间勾上就可以了，然后无障碍等待10秒就可以直接点确定，不需要真的等10秒

**Comment by yhlzkd** [comment]
> 如果是无障碍跳过的话，现在已经就支持了，手机管家-跳过警告时间勾上就可以了，然后无障碍等待10秒就可以直接点确定，不需要真的等10秒

好的，感谢回复
