### ISSUE TITLE
红米Note7pro部分功能不能用

### ISSUE THREAD

**Issue by AceMONKEY519** [yonghen/chimi-#29]
data分区已解密，不同于note7没解密data分区 但是note7的解锁第一次使用指纹支付可以使用，但高级电源键均无法使用，还有安全中心的设置也无法生效，
note7，最新开发内测版
note7pro，最新稳定版，

**Comment by yonghen** [comment]
edxp?

**Comment by AceMONKEY519** [comment]
太极面具版

yonghen <notifications@github.com> 于 2019年3月24日周日 22:36写道：

**Comment by AceMONKEY519** [comment]
> edxp?

重启第一次使用指纹可以用了，电源键高级重启还是无法使用。安全中心100分也不能用还是
