### ISSUE TITLE
隐藏应用后台提示会导致第三方音乐播放器无通知

### ISSUE THREAD

**Issue by MillionZBW** [yonghen/chimi-#3]
版本：mix2s稳定版10.2.1.0
bug：开启隐藏应用后台运行提示，第三方音乐播放器的通知不显示。
另外，大部分功能失效。

**Comment by yonghen** [comment]
隐藏后台运行目前的确有些问题;
ChiMi此版本适配MIUI开发版9.1.24，其他版本并未适配。
