### ISSUE TITLE
一点重启系统界面就关机

### ISSUE THREAD

**Issue by hzx19980513** [yonghen/chimi-#36]
如题 直接死机 得长按开机

**Comment by yonghen** [comment]
@hzx19980513 百分百复现？如果这样的话建议不重启系统界面，直接重启手机 。

**Comment by hzx19980513** [comment]
我连着试了三次都是这样 应该是百分百复现了

**Comment by caliban511** [comment]
同样遇到这样的问题，长按电源按键系统界面就会重启，很长时间后才能重新进入桌面。
