### ISSUE TITLE
关于高级重启菜单问题

### ISSUE THREAD

**Issue by soulmates** [yonghen/chimi-#4]
我用的太极Magisk版，使用ChiMi的时候严格按照提示要求添加安全中心系统界面等应用到太极。
大部分功能没问题，但高级重启菜单必须软重启才能生效，可软重启因为我的系统问题会无法搜索到GPS。
希望您可以检查一下是不是ChiMi的原因，我也在想办法对太极进行反馈。

**Comment by yonghen** [comment]
高级电源不显示，还是点击无反应，
Magisk版本是否为18+，是否关闭了selinux？

**Comment by soulmates** [comment]
Magisk为18.0，selinux为开启状态。

**Comment by yonghen** [comment]
关闭selinux应该就能使用了，下个太极magisk版会修复此问题

**Comment by soulmates** [comment]
那么关闭selinux会出现什么坏的后果

**Comment by soulmates** [comment]
我试过关闭，然后重启系统界面，无效。

**Comment by yonghen** [comment]
高级电源菜单没有显示吗？

**Comment by soulmates** [comment]
我上面说的做了之后，无效

**Comment by soulmates** [comment]
这个SELinux的开关是即时生效的吗？

**Comment by yonghen** [comment]
是即时生效，现在我想确定一下的是：开启高级电源菜单功能，连高级电源菜单显示都没有，还是显示了高级电源菜单，但是重启至恢复模式和引导模式功能无效

**Comment by soulmates** [comment]
不显示高级电源菜单

**Comment by yonghen** [comment]
应该是其他模块占用了system分区，要么就是其他问题了，后续改进吧
