### ISSUE TITLE
反馈重量级BUG，chimi模块和 中国移动、云闪付 有冲突

### ISSUE THREAD

**Issue by 06ji** [yonghen/chimi-#40]
中国移动和云闪付 卡屏，去勾chimi模块就能正常打开，大佬看下什么问题

**Comment by 06ji** [comment]
忘了说下，小米9，MIUI android 9.0

**Comment by yonghen** [comment]
米6 测试是正常的... @06ji

**Comment by 06ji** [comment]
> 米6 测试是正常的... @06ji

找了小米5 android8.0 测试下，还是不行，EDXP群内很多人反映是打勾chimi是用不了中国移动和国内版的云闪付

顺便更新了chimi版本，也不行，还特意去勾所有模块，保留chimi，重启后，测试打开上述两个APP还是卡屏

**Comment by yonghen** [comment]
@06ji  我在太极环境测试的。。。你们试试打开或者关闭核心破解试试

**Comment by 06ji** [comment]
> @06ji 我在太极环境测试的。。。你们试试打开或者关闭核心破解试试

太极你有把中国移动和云闪付添加到名单吗，要加入他们。。。核心破解这个没开

**Comment by 06ji** [comment]
> @06ji 我在太极环境测试的。。。你们试试打开或者关闭核心破解试试

原则上，EDXP黑名单功能把两个APP打勾了应该可以打开，不知道chimi模块哪个代码干扰了EDXP黑名单功能。。

**Comment by jzw3131** [comment]
> @06ji 我在太极环境测试的。。。你们试试打开或者关闭核心破解试试

chimi和交通银行冲突，我启用chimi的时候交通银行app卡启动，去掉chimi交通银行能正常打开，没有加入任何黑名单，小米8，MIUI，Android 9。

**Comment by jzw3131** [comment]
> @06ji 我在太极环境测试的。。。你们试试打开或者关闭核心破解试试

chimi和交通银行冲突，我启用chimi的时候交通银行app卡启动，去掉chimi交通银行能正常打开，没有加入任何黑名单，小米8，MIUI，Android 9。
