### ISSUE TITLE
chimi与MIUI10 9.7.16版本冲突

### ISSUE THREAD

**Issue by jzw3131** [yonghen/chimi-#41]
只要勾选chimi模块，就会造成桌面强制停止，已无法正常使用。
小米8，Android9.0，MIUI10内测开发版。

**Comment by yonghen** [comment]
太极：太极app里把系统桌面移除；edxp：黑名单加入系统桌面或者白名单移除系统桌面。
如果不可行只能先卸载ChiMi了

**Comment by leochen522** [comment]
求大神继续更新 -
