### ISSUE TITLE
下拉时钟显秒与自定义时钟样式冲突

### ISSUE THREAD

**Issue by lgq-lzw** [yonghen/chimi-#55]
由于“时钟显秒”功能和“状态栏时钟样式开关”两功能互斥，而“下拉时钟”需“时钟显秒”打开，“时钟样式”需“状态栏时钟样式开关”打开，所以无法做到状态栏自定义样式情况下，下拉菜单也显秒。

而com.tianma.tweaks.miui这个插件可以实现状态栏与下拉时钟均自定义显秒，不过它的其余功能太弱、比不上吃米。

希望吃米能完善一下。

最好锁屏界面(默认主题)也能显秒

**Comment by yonghen** [comment]
新版本已修改

**Comment by lgq-lzw** [comment]
锁屏界面(默认主题)还是不能显秒
