### ISSUE TITLE
可以把系统下载管理某些情况WiFi才能继续下载的限制去掉嘛

### ISSUE THREAD

**Issue by huazhaozhe** [yonghen/chimi-#56]
比如系统更新固件下载完整包的时候,必须要连着WiFi才能继续下载☺

**Comment by yonghen** [comment]
下载管理-设置-数据网络下载限制设置成无限制就好了

**Comment by huazhaozhe** [comment]
> 下载管理-设置-数据网络下载限制设置成无限制就好了

emm很久了我记得以前设置了无限制也要连接WiFi才可以,好像是Google play更新/下载的时候会出现,所以来提了这个issue
现在貌似没有遇到过这个情况了
