### ISSUE TITLE
安全中心锁定100分功能失效

### ISSUE THREAD

**Issue by 1814239758** [yonghen/chimi-#57]
安全中心3.60生效，之后的版本锁定100分功能失效
复现概率：100％
其他功能：正常
模块激活：正常
设备：Redmi Note 7 Pro
MIUI版本：MIUI开发版12.12
edxposed环境：v0.4.6.1(4504)- tdgptedc( SandHook)
magisk环境：magisk20.3 official
root：magisk root已授权
手机管家（安全中心）APP版本：4.2.2

**Comment by yonghen** [comment]
@1814239758 新版本应该可以了
