### ISSUE TITLE
大佬求适配miui12 拆分通知音量，目前显示有点不正常 chimi永远滴神

### ISSUE THREAD

**Issue by JasonleeQAQ** [yonghen/chimi-#59]
大佬求适配miui12 拆分通知音量，目前显示有点不正常 chimi永远滴神

**Comment by yonghen** [comment]
显示不正常调下宽度试试

**Comment by yonghen** [comment]
> 大佬求适配miui12 拆分通知音量，目前显示有点不正常 chimi永远滴神

显示不正常调下宽度试试

**Comment by JasonleeQAQ** [comment]
宽度调节在12上挂掉了，100-600没有任何变化，同时挂掉的还有音量阶数调节，目前就发现这两个问题

**Comment by yonghen** [comment]
> 宽度调节在12上挂掉了，100-600没有任何变化，同时挂掉的还有音量阶数调节，目前就发现这两个问题

目前猜测是修改宽度部分代码变化了，适配miui12还需要些时间。
