### ISSUE TITLE
关于xposed无法激活

### ISSUE THREAD

**Issue by xinyonghu1** [yonghen/chimi-#6]
更新后的两个版本xposed无法激活，重新勾选重启也显示未激活，卸载xposed安装magisk太极才可以用，这是xposed里面的日志：Failed to load class chili.xposed.chimi.hooks.Hook

**Comment by yonghen** [comment]
已发布新版本，可能修复了

**Comment by xinyonghu1** [comment]
@yonghen  谢谢作者，辛苦啦

**Comment by xinyonghu1** [comment]
@yonghen 现在状态栏所有修改均无效 😭

**Comment by yonghen** [comment]
> @yonghen 现在状态栏所有修改和2.2.14后更新的功能均无效 😭（只有用太极才可以）

我这边的人测试功能正常啊

**Comment by xinyonghu1** [comment]
@yonghen 那可能是我系统问题了😭

**Comment by yonghen** [comment]
> @yonghen那可能是我系统问题了😭

基于MIUI开发版9.1.24，你是什么版本

**Comment by xinyonghu1** [comment]
@yonghen 8.11.2，不敢更新了，上次更新进Twrp，和自动解密发生冲突，直接进不了系统，线刷回来，数据全丢，怕了

**Comment by xinyonghu1** [comment]
@ @yonghen 然后我发现用太极所有功能都能用了😭
