### ISSUE TITLE
大佬请修复下小米10的一些bug

### ISSUE THREAD

**Issue by lsm3323203** [yonghen/chimi-#60]
每次重启手机，WiFi连接就卡主！
双排网速，隐藏/s等都无效果！

**Comment by yonghen** [comment]
> 每次重启手机，WiFi连接就卡主！
> 双排网速，隐藏/ s等都无效果！

miui 3.26开发版吗，更新miui版本后还是这样？

**Comment by lsm3323203** [comment]
我是小米10开发版内测版本，20.3.28
每次重启wifi都要卡连接，需要关闭再打开wifi才可以连接上，停用chimi就正常！某些功能不生效，不就知道是小米10的原因，还是系统问题，最后建议增加个时间居中的功能！



---原始邮件---
发件人: "yonghen"<notifications@github.com&gt;
发送时间: 2020年4月27日(周一) 晚上10:45
收件人: "yonghen/chimi-"<chimi-@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"lsm3323203"<150458919@qq.com&gt;;
主题: Re: [yonghen/chimi-] 大佬请修复下小米10的一些bug (#60)




  
每次重启手机，WiFi连接就卡主！
 双排网速，隐藏/ s等都无效果！
  
miui 3.26开发版吗，更新miui版本后还是这样？

**Comment by yonghen** [comment]
> 我是小米10开发版内测版本，20.3.28 每次重启wifi都要卡连接，需要关闭再打开wifi才可以连接上，停用chimi就正常！某些功能不生效，不就知道是小米10的原因，还是系统问题，最后建议增加个时间居中的功能！
> […](#)
> ---原始邮件--- 发件人: "yonghen"<notifications@github.com&gt; 发送时间: 2020年4月27日(周一) 晚上10:45 收件人: "yonghen/chimi-"<chimi-@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"lsm3323203"<150458919@qq.com&gt;; 主题: Re: [yonghen/chimi-] 大佬请修复下小米10的一些bug (#60) 每次重启手机，WiFi连接就卡主！ 双排网速，隐藏/ s等都无效果！ miui 3.26开发版吗，更新miui版本后还是这样？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

目前不知道原因，可能有些地方不兼容，如果更新MIUI版本后还出现连接WIFI卡死，最好能双清重刷完整包再反馈一下，对你手机产生的影响我很抱歉。

**Comment by lsm3323203** [comment]
刚开始用chimi，wifi正常的，部分功能也是会无效，我是最近更新的几个版本，才会导致wifi出问题的！
