### ISSUE TITLE
最新版似乎无法使用edxposed激活

### ISSUE THREAD

**Issue by zonghongdog** [yonghen/chimi-#62]
无论如何都无法激活

**Comment by Actuallymax** [comment]
可以的

**Comment by TTTPOB** [comment]
> 可以的

我也遇到无法使用的问题，edxposed manager中打开模块开关后，chimi依然显示未激活，并且忽略提示后，勾选功能并不生效

**Comment by yonghen** [comment]
> > 可以的
> 
> 我也遇到无法使用的问题，edxposed manager中打开模块开关后，chimi依然显示未激活，并且忽略提示后，勾选功能并不生效

清除Chimi数据重新勾选，并重启手机
