### ISSUE TITLE
希望可以加一个恢复MIUI11全面屏手势的开关

### ISSUE THREAD

**Issue by WhiteLeaf36** [yonghen/chimi-#67]
MIUI12小白条的全面屏手势感觉不如MIUI11侧滑停顿返回上个应用那种好用，经测试使用旧版系统桌面可以使用原来的手势，但是就没有自由小窗了，希望大佬可以做一个能保留自由小窗的手势切换开关（
用MIUI12的系统桌面应该就能实现，在设置里隐藏小白条的时候下面会闪过侧滑停顿返回上个应用的开关，所以功能还是保留的，就是系统文件里找不到从哪打开..谢谢大佬

**Comment by yonghen** [comment]
无能为力，我用的是米6，手势我从来没用过，升级到MIUI12后我手机好像也没有相关的快速切换

**Comment by WhiteLeaf36** [comment]
好的..谢谢大佬
