### ISSUE TITLE
【非问题】一大堆提意见的不烦么

### ISSUE THREAD

**Issue by Mariobolo** [yonghen/chimi-#69]
一大堆提意见的，
没有一点建树工作或者能提供额外帮助的，
你们不烦么，有问题加群提问呐，
从以前 关注这个项目，吊事儿没有，
现在重新更新，不开放，一群在这里提屌问题的，
发来的邮件不是项目更新了，
是一堆垃圾

**Comment by SkyYkb** [comment]
GitHub在关注时选择Releases Only就可以不接收Issues通知了。
