### ISSUE TITLE
双排网速没有效果，只能改变字体大小

### ISSUE THREAD

**Issue by cystc2008** [yonghen/chimi-#83]
双排网速没有效果，只能改变字体大小

**Comment by TroubleWind** [comment]
同样的问题，小米10，MIUI12稳定版12.0.4.0，只缩小显示单排
![Y9EP24TIXRUFBYE~BY796EV](https://user-images.githubusercontent.com/16570023/89260519-00b01b80-d65f-11ea-9087-89b50ce8219c.jpg)

**Comment by HinataKato** [comment]
红木K30 5G MIUI eu 12.0.5.0 Edxposed 0.4.6.2 YAHFA 可以用
![Screenshot_2020-08-20-14-22-06-115_com android chrome_1](https://user-images.githubusercontent.com/57648531/90724250-d1510e00-e2f0-11ea-84b7-59ec2c4e5beb.jpg)
