### ISSUE TITLE
可以适配edxposed吗？

### ISSUE THREAD

**Issue by jzw3131** [yonghen/chimi-#9]
小米8 Android9.0 开发版9.2.21，edxp全局模式，启用chimi后开机几秒就黑屏，希望开发者有余力的话能够适配下黑/白名单模式，因为需要过滤一些如云闪付、中国移动等软件的检测，谢谢。

**Comment by yonghen** [comment]
目前无法解决，没有足够的时间测试，尝试过edxposed，要么刷入卡米，要么激活chimi卡米

**Comment by xinyonghu1** [comment]
可以适配啊

**Comment by jzw3131** [comment]
目前可以用了，之前是edxp的bug没有生效，更新后可以，能加入显秒功能吗
