### ISSUE TITLE
太极环境下 ChiMi_3.07.07 导致系统界面卡顿问题

### ISSUE THREAD

**Issue by Bonnie-Ran** [yonghen/chimi-#96]
設備: MI 9+MIUI 10 9.5.23星空包+Android 9
bug: 1.UI隨手機使用時間的增長越來越卡頓;
         2.重啟可恢復，然後繼續1。

**Comment by Jun041** [comment]
9.5.23星空包，为啥要用3.07.07版本？你这是安卓9的系统，不是应该使用基于“安卓9 MIUI10版本”适配的chimi吗?


看更新说明啊，以下这个版本基于9.6.13，你的版本是9.5.23，两个都是2016年，一个是6月13，一个是5月23，很接近啊。

v2.6.21
 v2.6.21
 a6e7546
@yonghen yonghen released this on 21 Jun 2019 · 15 commits to master since this release

此版本基于MIUI10 9.6.13 Android9.0 适配开发，其他版本可能会有部分功能或全部功能失效。

更新内容：
1.新增桌面应用文字隐藏功能
2.新增状态栏4G可修改成5G功能（仅仅是修改文字）
3.新增去部分主题广告功能
4.新增禁止还原电池优化功能
5.新增打开系统隐藏的极致省电模式功能
6.新增全球上网过Root检测功能
7.新增状态栏添加CPU/电池温度功能（已知bug：部分机型可能会出现0℃）
8.新增LCD息屏显示功能（LCD屏开启息屏显示的沙雕功能）

为什么说暂停更新，现在又更新呢？
测试版已被其他人上传发布网络上，所以在GitHub干脆再更新一次。
这将是MIUI10最后一版。

**Comment by Jun041** [comment]
上面是2019年，手抖打错了（不是2016）。


吃米版本太新你系统却用着老古董系统，出现不兼容或异常卡顿或其他莫名其妙的问题，很正常。。。


人往高处走水往低处流，软件都是跟随着系统版本的更新而随着适配，你提交Issue，是想等吃米作者修复吗，但问题是，可能没几个人（没多少人吧，很少很少）会跟你一样停留在【安卓9 MIUI10】的老古董系统，


不是吃米有问题，是你的系统版本有问题，你不肯更新系统导致的有问题，，或者说你搭配有问题，最新版本吃米（你这个是倒数第二新，最新是4.0.18，你是第二新），系统却不是最新，MIUI12.5 安卓11.0都出来了，你不是用着MIUI12，也不是用着MIUI11，却用着MIUI10。。。

**Comment by Bonnie-Ran** [comment]
謝謝哥哥解答，非常感謝，我只關注添加的新功能呢，沒有注意基於手機系統版本更新的信息，那個那個我用星空包還是Android 9是因為這個版本做的比較精簡，我自己在原來的基礎上又精簡呢一下，而且bug比較少，配合某些控制權限的軟件使用體驗很不錯，然後我用ChiMI是奔著狀態欄時間顯秒和顯示電池溫度去噠，而且有點強迫症，電池溫度在狀態欄右邊才好看，按照你的思路我最後選擇了3.06.12，這個版本可以選擇電池溫度的位置，我用著暫時沒有明顯的bug，最後還是非常感謝你啊！(默默說一句，Android 9不算老古董吧 /委屈巴巴)

**Comment by Jun041** [comment]
安卓9算老古董了，，我个人觉得是😂，虽然现在小米9是安卓11.0，你现在是安卓9.0，中间就差了一个安卓10.0。


但是，并非只差了一个版本那么简单。安卓版本是只有一个。会用小米开发版的人都知道，开发版内测一周更新4个版本，两周就8个版本，一个月4周那就是16个版本，你是9.5.23，这是2019年5月23号的版本，现在是2021年1月24号，距离最后一个安卓10.0开发版，也就是MIUI12 20.12.9，2020年12月9号的版本，这差距有一年6，7个月，一个月就16个开发内测包，18个月，这得多少个开发版版本？


我说“安卓9”是老古董，其实主要是想表达“安卓9的MIUI10系统”是老古董，确切来说，重点是“MIUI10系统”是老古董，安卓版本是只差了一个，但MIUI版本可差了不止一个，MIUI系统，开发版内测一周4个更新，开发版公测每周一个更新，如果按公测算，一个月也有4个包，你这9.5.23距离20.12.9，有18个月之差呢😂，那就是72个开发版的差距。


然后，每周开发版一个版本，MIUI系统内部很多系统文件都在变，更何况累计18个月之久的差距。“老古董”主要指这些。安卓版本，是差一个，但众所周知，MIUI Flyme，colour os，EMUI，等等，这些全都是基于谷歌打造的安卓系统，进行魔改的系统，并非只有跨安卓版本，才差距很大，就算是同安卓版本，随着时间不断推移，随着系统版本的不断更新、不断累积，那差距也会很大很大的，要不然不会用上魔改这个词，经过魔改后，跟原先的原生类原生（谷歌原版系统），差距已经很大了，原生类原生简洁，国内系统相对比较臃肿，但各方各面功能也很齐全，原生类原生，可以说是简洁，但也可以用简陋二字形容，不太符合国人的使用习惯。所以，我建议你适当地更新一下，MIUI10系统确实，我个人觉得算比较老古董了，安卓版本不算太重要。重点是MIUI大版本之差距，MIUI10→MIUI11→MIUI12，MIUI11就有好几十个版本了，MIUI12也是，MIUI10本身也有好几十个。


你用的3.07.07版本吃米，作者就是基于MIUI12开发版打造的，你用MIUI10系统去适应这个“最新版本吃米”，我个人觉得效果会没有那么理想，甚至冒出莫名其妙的bug，也很正常。

**Comment by Bonnie-Ran** [comment]
謝謝哥哥科普，解釋的好詳細哦，你這麼一說，確實距離最新版已經有1年多的時間了哎，感覺哥哥好厲害，現在還給小白這麼耐心解釋的人不多了哎，最後謝謝哥哥科普，新年快樂啊~😋

**Comment by lgq-lzw** [comment]
这样的版本区分导致很多用户使用不便的。习惯上都追着新版本。
有可能是Jun041所讲原因导致，新版的吃米在我系统上有若干功能无法实现。
我现在是CustoMIUIzer+吃米混用，CustoMIUIzer更新频繁，同一功能兼容各版MIUI，不会抛弃老MIUI。而吃米可以实现自定义日期时间样式。
话说，4.01.18版的吃米在MIUI11上“系统界面”功能全部失效，要恢复到3.07.07才可以。
而且，对于riru+edxposed架构，每次更新新版riru后，吃米模块就会失效，需要在宿主edxposed里停用吃米，重启手机，再启用吃米才能重新生效。而我手机上其他xposed模块没有此问题。
我两台手机：红米6A(MIUI11)+红米Note8(MIUI11)
